AWSTemplateFormatVersion: '2010-09-09'
Description: Replica databases e crawlers da conta origem

Resources:
# Banco de dados do Glue (1 de 23)
  IGAPipefyBoxeDB:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: "416046234086"  # ← substituir pelo ID da conta do IGA
      DatabaseInput:
        Name: "iga-pipefy-boxe-db"
        Description: "Banco de dados migrado da conta de origem"
        CreateTableDefaultPermissions:
          - Principal:
              DataLakePrincipalIdentifier: "IAM_ALLOWED_PRINCIPALS"
            Permissions:
              - "ALL"

# Banco de dados do Glue (2 de 23)
  IGAPipefyBrasilandiaDB:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: "416046234086"  # ← substituir pelo ID da conta do IGA
      DatabaseInput:
        Name: "iga-pipefy-brasilandia-db"
        Description: "Banco de dados migrado da conta de origem"
        CreateTableDefaultPermissions:
          - Principal:
              DataLakePrincipalIdentifier: "IAM_ALLOWED_PRINCIPALS"
            Permissions:
              - "ALL"

# Banco de dados do Glue (3 de 23)
  IGAPipefyEptBasqueteGinasioEsportesDB:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: "416046234086"  # ← substituir pelo ID da conta do IGA
      DatabaseInput:
        Name: "iga-pipefy-ept-basquete-ginasio-esportes-db"
        Description: "Banco de dados migrado da conta de origem"
        CreateTableDefaultPermissions:
          - Principal:
              DataLakePrincipalIdentifier: "IAM_ALLOWED_PRINCIPALS"
            Permissions:
              - "ALL"

# Banco de dados do Glue (4 de 23)
  IGAPipefyEptFutsalBairroPadreEternoDB:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: "416046234086"  # ← substituir pelo ID da conta do IGA
      DatabaseInput:
        Name: "iga-pipefy-ept-futsal-bairro-padre-eterno-db"
        Description: "Banco de dados migrado da conta de origem"
        CreateTableDefaultPermissions:
          - Principal:
              DataLakePrincipalIdentifier: "IAM_ALLOWED_PRINCIPALS"
            Permissions:
              - "ALL"

# Banco de dados do Glue (5 de 23)
  IGAPipefyEptFutsalGinasioEsportesDB:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: "416046234086"  # ← substituir pelo ID da conta do IGA
      DatabaseInput:
        Name: "iga-pipefy-ept-futsal-ginasio-esportes-db"
        Description: "Banco de dados migrado da conta de origem"
        CreateTableDefaultPermissions:
          - Principal:
              DataLakePrincipalIdentifier: "IAM_ALLOWED_PRINCIPALS"
            Permissions:
              - "ALL"

# Banco de dados do Glue (6 de 23)
  IGAPipefyEptGinasticaGinasioEsportesDB:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: "416046234086"  # ← substituir pelo ID da conta do IGA
      DatabaseInput:
        Name: "iga-pipefy-ept-ginastica-ginasio-esportes-db
        Description: "Banco de dados migrado da conta de origem"
        CreateTableDefaultPermissions:
          - Principal:
              DataLakePrincipalIdentifier: "IAM_ALLOWED_PRINCIPALS"
            Permissions:
              - "ALL"

# Banco de dados do Glue (7 de 23)
  IGAPipefyEptRitmosDB:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: "416046234086"  # ← substituir pelo ID da conta do IGA
      DatabaseInput:
        Name: "iga-pipefy-ept-ritmos-db"
        Description: "Banco de dados migrado da conta de origem"
        CreateTableDefaultPermissions:
          - Principal:
              DataLakePrincipalIdentifier: "IAM_ALLOWED_PRINCIPALS"
            Permissions:
              - "ALL"

# Banco de dados do Glue (8 de 23)
  IGAPipefyEptVoleiGinasioEsportesDB:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: "416046234086"  # ← substituir pelo ID da conta do IGA
      DatabaseInput:
        Name: "iga-pipefy-ept-volei-ginasio-esportes-db"
        Description: "Banco de dados migrado da conta de origem"
        CreateTableDefaultPermissions:
          - Principal:
              DataLakePrincipalIdentifier: "IAM_ALLOWED_PRINCIPALS"
            Permissions:
              - "ALL"

# Banco de dados do Glue (9 de 23)
  IGAPipefyGuaratinguetaAlcinaSoaresDB:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: "416046234086"  # ← substituir pelo ID da conta do IGA
      DatabaseInput:
        Name: "iga-pipefy-guaratingueta-alcina-soares-db"
        Description: "Banco de dados migrado da conta de origem"
        CreateTableDefaultPermissions:
          - Principal:
              DataLakePrincipalIdentifier: "IAM_ALLOWED_PRINCIPALS"
            Permissions:
              - "ALL"

# Banco de dados do Glue (10 de 23)
  IGAPipefyGuaratinguetaAnaFaustaDB:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: "416046234086"  # ← substituir pelo ID da conta do IGA
      DatabaseInput:
        Name: "iga-pipefy-guaratingueta-ana-fausta-db"
        Description: "Banco de dados migrado da conta de origem"
        CreateTableDefaultPermissions:
          - Principal:
              DataLakePrincipalIdentifier: "IAM_ALLOWED_PRINCIPALS"
            Permissions:
              - "ALL"

# Banco de dados do Glue (11 de 23)
  IGAPipefyGuaratinguetaMariaAparecidaDB:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: "416046234086"  # ← substituir pelo ID da conta do IGA
      DatabaseInput:
        Name: "iga-pipefy-guaratingueta-maria-aparecida-db"
        Description: "Banco de dados migrado da conta de origem"
        CreateTableDefaultPermissions:
          - Principal:
              DataLakePrincipalIdentifier: "IAM_ALLOWED_PRINCIPALS"
            Permissions:
              - "ALL"

# Banco de dados do Glue (12 de 23)
  IGAPipefyGuaratinguetaMariaJuliaDB:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: "416046234086"  # ← substituir pelo ID da conta do IGA
      DatabaseInput:
        Name: "iga-pipefy-guaratingueta-maria-julia-db"
        Description: "Banco de dados migrado da conta de origem"
        CreateTableDefaultPermissions:
          - Principal:
              DataLakePrincipalIdentifier: "IAM_ALLOWED_PRINCIPALS"
            Permissions:
              - "ALL"

# Banco de dados do Glue (13 de 23)
  IGAPipefyMulherPeriferia:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: "416046234086"  # ← substituir pelo ID da conta do IGA
      DatabaseInput:
        Name: "iga-pipefy-mulher-periferia"
        Description: "Banco de dados migrado da conta de origem"
        CreateTableDefaultPermissions:
          - Principal:
              DataLakePrincipalIdentifier: "IAM_ALLOWED_PRINCIPALS"
            Permissions:
              - "ALL"

# Banco de dados do Glue (14 de 23)
  IGAPipefyPmqEventosDB:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: "416046234086"  # ← substituir pelo ID da conta do IGA
      DatabaseInput:
        Name: "iga-pipefy-pmq-eventos-db"
        Description: "Banco de dados migrado da conta de origem"
        CreateTableDefaultPermissions:
          - Principal:
              DataLakePrincipalIdentifier: "IAM_ALLOWED_PRINCIPALS"
            Permissions:
              - "ALL"

# Banco de dados do Glue (15 de 23)
  IGAPipefyPmqFotografiaDB:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: "416046234086"  # ← substituir pelo ID da conta do IGA
      DatabaseInput:
        Name: "iga-pipefy-pmq-fotografia-db"
        Description: "Banco de dados migrado da conta de origem"
        CreateTableDefaultPermissions:
          - Principal:
              DataLakePrincipalIdentifier: "IAM_ALLOWED_PRINCIPALS"
            Permissions:
              - "ALL"

# Banco de dados do Glue (16 de 23)
  IGAPipefyPmqMidiasDB:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: "416046234086"  # ← substituir pelo ID da conta do IGA
      DatabaseInput:
        Name: "iga-pipefy-pmq-midias-db"
        Description: "Banco de dados migrado da conta de origem"
        CreateTableDefaultPermissions:
          - Principal:
              DataLakePrincipalIdentifier: "IAM_ALLOWED_PRINCIPALS"
            Permissions:
              - "ALL"

# Banco de dados do Glue (17 de 23)
  PipefyEscolaSorocabaDB:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: "416046234086"  # ← substituir pelo ID da conta do IGA
      DatabaseInput:
        Name: "pipefy_escola_sorocaba_db"
        Description: "Banco de dados migrado da conta de origem"
        CreateTableDefaultPermissions:
          - Principal:
              DataLakePrincipalIdentifier: "IAM_ALLOWED_PRINCIPALS"
            Permissions:
              - "ALL"

  # Crawler do Glue - iga-pipefy-boxe-crawler
  IGAPipefyBoxeCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: "iga-pipefy-boxe-crawler"
      Role: "arn:aws:iam::416046234086:role/role-glue-developer"  # substitua pelo ARN completo da role na conta destino
      DatabaseName: "iga-pipefy-boxe-db"
      Targets:
        S3Targets:
          - Path: "s3://iga-pipefy-boxe"
            Exclusions: []
      RecrawlPolicy:
        RecrawlBehavior: "CRAWL_EVERYTHING"
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
        DeleteBehavior: "DEPRECATE_IN_DATABASE"
      LineageConfiguration:
        CrawlerLineageSettings: "DISABLE"
      Configuration: |
        {
          "Version": 1.0,
          "CrawlerOutput": {
            "Partitions": {
              "AddOrUpdateBehavior": "InheritFromTable"
            }
          },
          "Grouping": {
            "TableGroupingPolicy": "CombineCompatibleSchemas",
            "TableLevelConfiguration": 3
          },
          "CreatePartitionIndex": true
        }
      LakeFormationConfiguration:
        UseLakeFormationCredentials: false

