AWSTemplateFormatVersion: '2010-09-09'
Description: Create three secure S3 buckets with safe deletion protections.

Parameters:
  BucketPrefix:
    Type: String
    Default: bs-bulklab
    Description: Prefix used to build globally-unique bucket names.

  EnvironmentTag:
    Type: String
    Default: Dev
    Description: Value for the Environment tag.

Mappings: {}

Resources:
  # 1) Data bucket
  DataBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub '${BucketPrefix}-data-${AWS::AccountId}-${AWS::Region}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentTag
        - Key: Name
          Value: !Sub '${BucketPrefix}-data'

  # 2) Artifacts bucket
  ArtifactsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub '${BucketPrefix}-artifacts-${AWS::AccountId}-${AWS::Region}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentTag
        - Key: Name
          Value: !Sub '${BucketPrefix}-artifacts'

  # 3) Logs bucket (can be used for future access logs or general logs)
  LogsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub '${BucketPrefix}-logs-${AWS::AccountId}-${AWS::Region}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentTag
        - Key: Name
          Value: !Sub '${BucketPrefix}-logs'

Outputs:
  DataBucketName:
    Description: Name of the data bucket
    Value: !Ref DataBucket
  ArtifactsBucketName:
    Description: Name of the artifacts bucket
    Value: !Ref ArtifactsBucket
  LogsBucketName:
    Description: Name of the logs bucket
    Value: !Ref LogsBucket
